version: '3.7'
services:
  livekit:
    container_name: "livekit"
    image: livekit/livekit-server:latest
    restart: unless-stopped
    command: --dev --bind 0.0.0.0 --config /etc/livekit.yaml
    ports:
      - 7880:7880
    volumes:
      - ./config.yaml:/etc/livekit.yaml
    networks:
      - livekit
networks:
  livekit:
    driver: bridge
